config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),  # postsへのルーティング
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),  # トップページのURLパターンと対応するビュー
    path('create/', views.CreateView.as_view(), name='create'),
]

posts/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
  content = models.TextField(blank=True)
  created_at = models.DateTimeField(verbose_name='投稿日時', default=timezone.now)

posts/forms.py
from .models import Post
from django import forms

class PostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ['content']

posts/views.py
from django.shortcuts import render,redirect
from django.views import View
from posts.models import Post
from .forms import PostForm

class IndexView(View):        
    def get(self,request,*args,**kwargs):
        posts =  Post.objects.all()  # すべてのレコードをpostsに代入
        return render(request, 'posts/index.html',{'posts':posts})
    
class CreateView(View):
  def get(self,request, *args, **kwargs):
    form = PostForm()
    return render(request, 'posts/create.html', {'form': form})

  #投稿内容を保存する
  def post(self, request, *args, **kwargs):
     form = PostForm(request.POST)
     #バリデーションのチェック
     if form.is_valid():
        #投稿に問題がなければ保存する
        form.save()
        #redirectで一覧画面に異動する
        return redirect('posts:index')

templates/posts/create.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/posts.css' %}">
</head>
<body>
  <h1>新規投稿ページ</h1>
  <form method="posts">
    {% csrf_token %}
    {{ form.content }}
    <button type="submit">投稿する</button>
  </form>
</body>

templates/posts/index.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/posts.css' %}">
</head>
<h1>Top page</h1>
<a href="{% url 'posts:create' %}">新規投稿</a>
{% for post in posts %}
  <div class="post">
    <div class="post-date">
      投稿日時：{{ post.created_at }}
    </div>
    <div class="post-content">
      {{ post.content }}
    </div>
  </div>
{% endfor %}